LHQUM/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path("user/", include("userauths.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from core.views import index, search_view, CreateUser, UpdateUser, DeleteUser

app_name = 'core'

urlpatterns = [
    path("", index, name='index'),
    path("search/", search_view, name='search'),
    path('create/', CreateUser.as_view(), name='CreateUser'),
    path('delete/<int:pk>/', DeleteUser.as_view(), name='DeleteUser'),
    path('update/<int:pk>/', UpdateUser.as_view(), name='UpdateUser'),

]

userauths/urls.py
from django.shortcuts import render
from django.urls import path
from userauths import views
from userauths.views import profile_update
app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path('edit-profile/', profile_update, name='edit-profile'),
]

templates/partials/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
    <script src="https://kit.fontawesome.com/8f6d25a064.js" crossorigin="anonymous"></script>
    <title>User Management</title>
</head>
<body>
    <main class="table" id="customers_table">
        <section class="table__header">
            <h1>
                <a href="{% url 'core:index' %}">Customer's Management</a>
            </h1>
            <div class="input-group">
                <form action="{% url 'core:search' %}" method="GET">
                    <input type="search" id="searchInput" placeholder="Search Data..." name="q">
                    <button type="submit"><i class="fas fa-search"></i></button>
                </form>
                <div>
					{% if messages %}
					<div id="messages">
						{% for message in messages %}
						<div class="alert {{ message.tags }}">
							{{ message }}
						</div>
						{% endfor %}
					</div>
					{% endif %}
                </div>
            </div>
            <div class="export__file">
                <label for="export-file" title="Export File"><i class="fa-solid fa-gear"></i></label>
                <input type="checkbox" id="export-file">
                <div class="export__file-options">
                    {% if request.user.is_authenticated %}
                        <label>{{ request.user.username }}</label>
                        {% if request.user.is_superuser %}
                            <label for="export-file" id="toPDF"><a href="{% url 'core:CreateUser' %}">Create User</a></label>
                        {% endif %}
                        <label for="export-file" id="toPDF"><a href="{% url 'userauths:sign-out' %}">Sign out</a></label>
                        <!-- Hiển thị nút Edit Profile -->
                        <label for="edit-profile" id="toPDF"><a href="{% url 'userauths:edit-profile' %}">Edit Profile</a></label>
                    {% else %}
                        <label>Account</label>
                        <label for="export-file" id="toPDF"><a href="{% url 'userauths:sign-in' %}">Register</a></label>
                    {% endif %}
                </div>
            </div>
            
        </section>
        {% block content %}
        {% endblock content %}
    </main>
    <script>
        setTimeout(function() {
            var messages = document.getElementById('messages');
            if (messages) {
                messages.style.display = 'none';
            }
        }, 4000); // 5000 milliseconds = 5 seconds
    </script>
</body>
</html> 