LHQUM/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path("user/", include("userauths.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from core.views import index, search_view, CreateUser, UpdateUser, DeleteUser

app_name = 'core'

urlpatterns = [
    path("", index, name='index'),
    path("search/", search_view, name='search'),
    path('create/', CreateUser.as_view(), name='CreateUser'),
    path('delete/<int:pk>/', DeleteUser.as_view(), name='DeleteUser'),
    path('update/<int:pk>/', UpdateUser.as_view(), name='UpdateUser'),

]

userauths/urls.py
from django.shortcuts import render
from django.urls import path
from userauths import views
from userauths.views import profile_update
app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path('edit-profile/', profile_update, name='edit-profile'),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)  
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        
        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    address = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']
    
    objects = UserManager()
    
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

userauths/forms.py
from django.utils import timezone
import datetime
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
import re
User = get_user_model()

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username"}),max_length=20)
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "First Name"}), max_length=30)
    last_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Last Name"}), max_length=30)
    phone_number = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Phone Number"}), max_length=20, required=False)
    address = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Address"}), max_length=255, required=False)
    birth_date = forms.DateField(widget=forms.DateInput(attrs={"placeholder": "Select Birth Date", "type": "date"}), required=False)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}))
    
    def clean_username(self):
        username = self.cleaned_data.get('username', '')

        # Kiểm tra độ dài username
        if len(username) > 12:
            raise forms.ValidationError('Username should be at most 12 characters long.')

        # Kiểm tra xem username chỉ chứa chữ cái và số (không chứa ký tự đặc biệt)
        if not re.match(r'^[a-zA-Z0-9]+$', username):
            raise forms.ValidationError('Username should contain only letters and digits.')

        return username
        
    def clean_email(self):
        email = self.cleaned_data.get('email', '')

        # Kiểm tra xem email có chứa ký tự '@' không
        if '@' not in email:
            raise forms.ValidationError('Invalid email format: missing "@" character.')

        # Kiểm tra xem email có kết thúc bằng '@gmail.com' hoặc '@outlook.com'
        if not email.endswith('@gmail.com') and not email.endswith('@outlook.com'):
            raise forms.ValidationError('Email must end with @gmail.com or @outlook.com.')

        # Lấy phần tên email trước '@'
        username_part = email.split('@')[0]

        # Kiểm tra độ dài phần tên email trước '@'
        if len(username_part) > 30:
            raise forms.ValidationError('Email username part must be 30 characters or less.')

        # Kiểm tra xem email có chứa ký tự đặc biệt không
        if any(char in email for char in r"""!#$%&'*+/=?^_`{|}~"""):
            raise forms.ValidationError('Email should not contain special characters.')

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1', '')

        # Kiểm tra xem mật khẩu có chứa khoảng trắng không
        if ' ' in password1:
            raise forms.ValidationError('Password should not contain spaces.')

        # Kiểm tra xem mật khẩu có bắt đầu bằng khoảng trắng không
        if password1 and password1[0] == ' ':
            raise forms.ValidationError('Password should not start with a space.')

        # Kiểm tra xem mật khẩu có chứa ký tự '>' hoặc '<' không
        if '>' in password1 or '<' in password1:
            raise forms.ValidationError('Password should not contain ">" or "<" characters.')

        # Kiểm tra xem mật khẩu có chứa icon hoặc ký tự emoji không
        if re.search(r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251]', password1):
            raise forms.ValidationError('Password should not contain emoji or icon characters.')

        return password1
    
    def clean_birth_date(self):
        birth_date = self.cleaned_data.get('birth_date')

        if not birth_date:
            raise forms.ValidationError('Please select a birth date.')

        if isinstance(birth_date, str):
            try:
                # Chuyển đổi birth_date từ chuỗi sang đối tượng datetime.date
                birth_date = datetime.date.fromisoformat(birth_date)
            except ValueError:
                raise forms.ValidationError('Invalid date format.')
        elif not isinstance(birth_date, datetime.date):
            raise forms.ValidationError('Invalid date format.')

        # Kiểm tra nếu ngày sinh không phải là tương lai
        if birth_date > timezone.now().date():
            raise forms.ValidationError('The birth date cannot be in the future.')

        # Kiểm tra nếu ngày sinh không trước năm 1924
        earliest_date = datetime.date(1924, 1, 1)
        if birth_date < earliest_date:
            raise forms.ValidationError('The birth date cannot be before 1924.')

        return birth_date

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name').strip()
        if not re.match(r'^[a-zA-Z]+$', first_name):
            raise forms.ValidationError("First name should only contain letters and no spaces.")
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name').strip()
        if not re.match(r'^[a-zA-Z]+$', last_name):
            raise forms.ValidationError("Last name should only contain letters and no spaces.")
        return last_name
    
    def clean_address(self):
        address = self.cleaned_data.get('address').strip()
        if not address:
            raise forms.ValidationError("Address cannot be empty.")
        return address
    
    # điều kiện trường phone_number
    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')

        # Kiểm tra xem phone_number chỉ chứa các chữ số và có độ dài từ 10 đến 11 chữ số
        if not phone_number.isdigit() or len(phone_number) < 10 or len(phone_number) > 11:
            raise forms.ValidationError("Phone number should only contain digits and be between 10 to 11 characters long")
        # Kiểm tra xem phone_number bắt đầu bằng '09' hoặc '03'
        if not phone_number.startswith('09') and not phone_number.startswith('03'):
            raise forms.ValidationError("Phone number should start with '09' or '03'")
        return phone_number

    class Meta:
        model = User
        fields = [
            'username', 'email', 'first_name', 'last_name', 
            'phone_number', 'address', 'birth_date', 
            'password1', 'password2'
        ]

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.phone_number = self.cleaned_data['phone_number']
        user.address = self.cleaned_data['address']
        user.birth_date = self.cleaned_data['birth_date']
        
        if commit:
            user.save()
        return user

class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name','phone_number', 'address', 'birth_date', 'password']
    # điều kiện trường email
    def clean_email(self):
        email = self.cleaned_data.get('email', '')

        # Kiểm tra xem email có chứa ký tự '@' không
        if '@' not in email:
            raise forms.ValidationError('Invalid email format: missing "@" character.')

        # Kiểm tra xem email có kết thúc bằng '@gmail.com' hoặc '@outlook.com'
        if not email.endswith('@gmail.com') and not email.endswith('@outlook.com'):
            raise forms.ValidationError('Email must end with @gmail.com or @outlook.com.')

        # Lấy phần tên email trước '@'
        username_part = email.split('@')[0]

        # Kiểm tra độ dài phần tên email trước '@'
        if len(username_part) > 30:
            raise forms.ValidationError('Email username part must be 30 characters or less.')

        # Kiểm tra xem email có chứa ký tự đặc biệt không
        if any(char in email for char in r"""!#$%&'*+/=?^_`{|}~"""):
            raise forms.ValidationError('Email should not contain special characters.')

        return email
    # điều kiện trường username
    def clean_username(self):
        username = self.cleaned_data.get('username', '')

        # Kiểm tra độ dài username
        if len(username) > 12:
            raise forms.ValidationError('Username should be at most 12 characters long.')

        # Kiểm tra xem username chỉ chứa chữ cái và số (không chứa ký tự đặc biệt)
        if not re.match(r'^[a-zA-Z0-9]+$', username):
            raise forms.ValidationError('Username should contain only letters and digits.')

        return username
    # điều kiện trường phone_number
    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')

        # Kiểm tra xem phone_number chỉ chứa các chữ số và có độ dài từ 10 đến 11 chữ số
        if not phone_number.isdigit() or len(phone_number) < 10 or len(phone_number) > 11:
            raise forms.ValidationError("Phone number should only contain digits and be between 10 to 11 characters long")
        # Kiểm tra xem phone_number bắt đầu bằng '09' hoặc '03'
        if not phone_number.startswith('09') and not phone_number.startswith('03'):
            raise forms.ValidationError("Phone number should start with '09' or '03'")
        return phone_number
    # điều kiện trường password
    def clean_password(self):
        password = self.cleaned_data.get('password')
        # Check for any space in the password
        if ' ' in password:
            raise forms.ValidationError('Password should not contain any spaces.')
        # Check if password contains only allowed characters
        if not re.match(r'^[\w!@#$%^&*()_+=-]+$', password):

userauths/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from userauths.forms import ProfileForm, User, UserRegisterForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            # Lấy giá trị ngày sinh từ cleaned_data
            birth_date = form.cleaned_data.get('birth_date')
            new_user = form.save(commit=False)
            new_user.birth_date = birth_date
            new_user.save()

            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, Your account was created successfully.")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1'])
            login(request, new_user)
            return redirect("core:index")
    else:
        form = UserRegisterForm()

    context = {
        'form': form,
    }
    return render(request, "userauths/Register.html", context)

def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey you are already Logged In.")
        return redirect("core:index")

    if request.method == "POST":
        email = request.POST.get("email") # peanuts@gmail.com
        password = request.POST.get("password") # getmepeanuts

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in.")
                return redirect("core:index")
            else:
                messages.warning(request, "Email or Password incorrect! Try again!")

        except:
            messages.warning(request, f"User with {email} does not exist")


    return render(request, "userauths/Sign-in.html")

def logout_view(request):
    logout(request)
    messages.success(request, "You've logged out.")
    return redirect("core:index")

@login_required
def profile_update(request):
    profile = request.user  # Lấy thông tin người dùng hiện tại

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            update_session_auth_hash(request, request.user)  # Giữ người dùng đăng nhập sau khi cập nhật
            messages.success(request, "Profile Updated Successfully.")
            return redirect("core:index")  # Điều hướng về trang dashboard sau khi cập nhật thành công
    else:
        form = ProfileForm(instance=profile)

    context = {
        "form": form,
        "profile": profile,
    }

    return render(request, "userauths/Edit-profile.html", context)

templates/userauths/Edit-profile.html
{% extends 'partials/base.html' %}
{% load static %}
        {% block content %}
        <section class="table__body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
            <table>
                <tbody>
                    <tr>
                        <td colspan="2"><strong>Edit Profile</strong></td>
                    </tr>
                    <tr>
                        <td><strong>User Name</strong></td>
                        <td><input type="text" id="id_username" name="username" value="{{form.username.value}}" required></td>
                        {% if form.username.errors %}
                        <div class="error">{{ form.username.errors }}</div>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><strong>Email</strong></td>
                        <td><input type="email" id="id_email" name="email" value="{{form.email.value}}" required></td>
                        {% if form.email.errors %}
                        <div class="error">{{ form.email.errors }}</div>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><strong>First Name</strong></td>
                        <td><input type="text" id="id_first_name" name="first_name" value="{{form.first_name.value}}" required></td>
                        {% if form.first_name.errors %}
                        <div class="error">{{ form.first_name.errors }}</div>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><strong>Last Name</strong></td>
                        <td><input type="text" id="id_last_name" name="last_name" value="{{form.last_name.value}}" required></td>
                        {% if form.last_name.errors %}
                        <div class="error">{{ form.last_name.errors }}</div>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><strong>Phone Number</strong></td>
                        <td><input type="text" id="phone_number" name="phone_number" value="{{ form.phone_number.value }}" required></td>
                        {% if form.phone_number.errors %}
                        <div class="error">{{ form.phone_number.errors }}</div>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><strong>Address</strong></td>
                        <td><input type="text" id="address" name="address" value="{{form.address.value}}" required></td>
                        {% if form.address.errors %}
                        <div class="error">{{ form.address.errors }}</div>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><strong>Birth Date</strong></td>
                        <td>
                            <input type="date" id="birth_date" name="birth_date" value="{{ form.instance.birth_date|date:'Y-m-d' }}" required>
                            {% if form.birth_date.errors %}
                                <div class="error">{{ form.birth_date.errors }}</div>
                            {% endif %}
                        </td>
                    </tr>
                    
                    <tr>
                        <td><strong>Password</strong></td>
                        <td><input type="password" id="id_password" name="password" required></td>
                        {% if form.password.errors %}
                        <div class="error">{{ form.password.errors }}</div>
                        {% endif %}
                    </tr>

                    <tr>
                        <td colspan="2"><button type="submit">Update</button></td>
                        
                    </tr>
                </tbody>
            </table>
            </form>
        </section>
        {% endblock content %}

templates/userauths/Register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>Register</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link rel="stylesheet" href="{% static 'assets/css/log-reg.css' %}"/>
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>SignUp Form</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				<form action="{% url 'userauths:sign-up' %}" method="post">
          {% csrf_token %}
					<!-- <input class="text" type="text" name="Username" placeholder="Username" required=""> -->
          <div class="input-box">
          {{ form.username }}       
          </div>
          {% if form.username.errors %}
          <div class="error">{{ form.username.errors }}</div>
          {% endif %}
					<!-- <input class="text" type="text" name="Username" placeholder="Username" required=""> -->
          <div class="input-box">
          {{ form.first_name }}       
          </div>
          {% if form.first_name.errors %}
          <div class="error">{{ form.first_name.errors }}</div>
          {% endif %}
					<!-- <input class="text" type="text" name="Username" placeholder="Username" required=""> -->
          <div class="input-box">
          {{ form.last_name }}       
          </div>
          {% if form.last_name.errors %}
          <div class="error">{{ form.last_name.errors }}</div>
          {% endif %}
					<!-- <input class="text email" type="email" name="email" placeholder="Email" required=""> -->
          <div class="input-box">
          {{ form.email }}
          </div>
          {% if form.email.errors %}
          <div class="error">{{ form.email.errors }}</div>
          {% endif %}
					<!-- <input class="text email" type="email" name="email" placeholder="Email" required=""> -->
          <div class="input-box">
          {{ form.phone_number }}
          </div>
          {% if form.phone_number.errors %}
          <div class="error">{{ form.phone_number.errors }}</div>
          {% endif %}
					<!-- <input class="text email" type="email" name="email" placeholder="Email" required=""> -->
          <div class="input-box">
          {{ form.address }}
          </div>
          {% if form.address.errors %}
          <div class="error">{{ form.address.errors }}</div>
          {% endif %}
					<!-- <input class="text email" type="email" name="email" placeholder="Email" required=""> -->
          <div class="input-box">
          <p for="birth_date_picker">Birth date: </p> {{ form.birth_date }}
          </div>
          {% if form.birth_date.errors %} 
          <div class="error">{{ form.birth_date.errors }}</div>
          {% endif %}
					<!-- <input class="text" type="password" name="password" placeholder="Password" required=""> -->
          <div class="input-box">
          {{ form.password1 }}
          </div>
          {% if form.password1.errors %}
          <div class="error">{{ form.password1.errors }}</div>
          {% endif %}
					<!-- <input class="text w3lpass" type="password" name="password" placeholder="Confirm Password" required=""> -->
          <div class="input-box">
          {{ form.password2 }}
          </div>
          {% if form.password2.errors %}
          <div class="error">{{ form.password2.errors }}</div>
          {% endif %}
					<div class="wthree-text">
						<label class="anim">
							<input type="checkbox" class="checkbox" required="">
							<span>I Agree To The Terms & Conditions</span>
						</label>
						<div class="clear"> </div>
					</div>
					<input type="submit" name="register" value="Submit">
				</form>
				<p>Already have an Account? <a href="{% url 'userauths:sign-in' %}"> Login Now!</a></p>
			</div>
		</div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a> and edited by ...</p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

templates/userauths/Sign-in.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link rel="stylesheet" href="{% static 'assets/css/log-reg.css' %}"/>
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Login Form</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				
				<form action="{% url 'userauths:sign-in' %}" method="post">
					{% csrf_token %}
					{% if messages %}
					<div id="messages">
						{% for message in messages %}
						<div class="alert {{ message.tags }}">
							{{ message }}
						</div>
						{% endfor %}
					</div>
					{% endif %}
					<div class="input-box">
						<input class="text" type="text" name="email" placeholder="Enter your email" required="">
					</div>
					<div class="input-box">
						<input class="text" type="password" name="password" placeholder="Enter your password" required="">
					</div>
					<input type="submit" name="login" value="Sumbit">
				</form>
				<p>Don't have an Account? <a href="{% url 'userauths:sign-up' %}"> Register Now!</a></p>
			</div>
		</div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a> and edited by ...</p>
		</div>
		<script>
            setTimeout(function() {
                var messages = document.getElementById('messages');
                if (messages) {
                    messages.style.display = 'none';
                }
            }, 4000); // 5000 milliseconds = 5 seconds
        </script>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

templates/userauths/lockout.html
<!-- templates/lockout.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account Locked</title>
</head>
<body>
    <h1>Your account has been locked due to too many failed login attempts.</h1>
    <p>Please try again later.</p>
</body>
</html>